### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by DavideVito** [visualbuffer/copilot#3]
I've downloaded you project and changed the `file_path` attribute in the `frame.py` file, here's the code:

```
    file_path =  "Video/1min.mp4"# <== Upload appropriate file          
    video_out = "Output/1min.mov"

    frame =  FRAME( 
        ego_vehicle_offset = .15,
        yellow_lower = np.uint8([ 20, 50,   100]),
        yellow_upper = np.uint8([35, 255, 255]),
        white_lower = np.uint8([ 0, 200,   0]),
        white_upper = np.uint8([180, 255, 100]), 
        lum_factor = 118,
        max_gap_th = 0.45,
        YOLO_PERIOD = .25,
        lane_start=[0.35,0.75] , 
        verbose = 3)
    frame.process_video(file_path, 1,\
            video_out = video_out,pers_frame_time =144,\
            t0  =144 , t1 =150)#None)
```

Running the program, I got this error:

```
davidevitiello@iMac copilot % sudo python3 frame.py
2020-10-07 00:09:10.308022: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-10-07 00:09:10.330339: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fc4fff30b10 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-10-07 00:09:10.330371: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Video/1min.mp4 WIDTH 640 HEIGHT 360 FPS 29.97 DUR 59.0 s
Traceback (most recent call last):
  File "frame.py", line 313, in <module>
    frame.process_video(file_path, 1,\
  File "frame.py", line 242, in process_video
    self.image = self.image[:frame_h_out,:,:]
TypeError: 'NoneType' object is not subscriptable
```

How I do get rid of it? 

I do have `Python 3.7.3` installed on my system an iMac

**Comment by visualbuffer** [comment]
Set t0 less than 59( the length of the video )

**Comment by Liren666** [comment]
Sir, Nice job! But I have the same problem, and then I set t0 to 16, and it still reports an error. How to solve it?

Traceback (most recent call last):
  File "D:/GoogleDownload/copilot-master/copilot-master/frame.py", line 311, in <module>
    t0=16, t1=150)  # None)
  File "D:/GoogleDownload/copilot-master/copilot-master/frame.py", line 242, in process_video
    self.image = self.image[:frame_h_out,:,:]
TypeError: 'NoneType' object is not subscriptable

**Comment by pythonmjs** [comment]
I am facing the same issue. Did you already solve it? @Liren666
